# HMM topology for a non-speech unit (silence, laughter, ...)

states = [
    { id = 1, initweight = 1.0, finalweight = 0.0 },
    { id = 2, initweight = 0.0, finalweight = 0.0 },
    { id = 3, initweight = 0.0, finalweight = 0.0 }
    { id = 4, initweight = 0.0, finalweight = 0.0 }
    { id = 5, initweight = 0.0, finalweight = 1.0 }
]

links = [
    { src = 1, dest = 1, weight = 0.25 },
    { src = 1, dest = 2, weight = 0.25 },
    { src = 1, dest = 3, weight = 0.25 },
    { src = 1, dest = 4, weight = 0.25 },
    { src = 2, dest = 2, weight = 0.25 }
    { src = 2, dest = 3, weight = 0.25 }
    { src = 2, dest = 4, weight = 0.25 }
    { src = 2, dest = 5, weight = 0.25 }
    { src = 3, dest = 2, weight = 0.25 }
    { src = 3, dest = 3, weight = 0.25 }
    { src = 3, dest = 4, weight = 0.25 }
    { src = 3, dest = 5, weight = 0.25 }
    { src = 4, dest = 2, weight = 0.25 }
    { src = 4, dest = 3, weight = 0.25 }
    { src = 4, dest = 4, weight = 0.25 }
    { src = 4, dest = 5, weight = 0.25 }
    { src = 5, dest = 5, weight = 0.75 }
]

# If true, all states will have the same pdf.
tiestates = false
