# SPDX-License-Identifier: MIT

[model]
ncomponents = 5
covtype = "full" # "full" | "diagonal"
priortype = "categorical" # "categorical" | "stick-breaking"

[inference]
steps = 10
learning_rate = 1e-3
mini_batch_size = 100 # numbers of utterances per mini-batch
