# Configuration file for high-resolution MFCC features.

featype = "MFCC"
removedc = true
dithering = 0
srate = 16000
frameduration = 0.025
framestep = 0.01
preemphasis = 0.97
windowfn = "hann"
windowpower = 0.85
nfilters = 40
lofreq = 40
hifreq = 7600
addenergy = true
nceps = 40
liftering = 22

[Normalization]
mean_norm = true
