# Configuration file of the TDNN.

# Dropout level applied to each hidden layer.
dropout         = 0.2

# The following arrays are the configuration of the convolutional
# layers. Obviously, all of them should have the same size!!
dilations       = [  1,   1,   3,   3,   3]
kernel-sizes    = [  3,   3,   3,   3,   3]
#hidden-dims     = [384, 384, 384, 384, 384]
hidden-dims     = [256, 256, 256, 256, 256]
strides         = [  1,   1,   1,   1,   3]

