# LF-MMI training configuration file.

learning_rate = 1e-3
epochs = 40
mini_batch_size = 64

# Epoch until which to do curriculum training (i.e. sorting utterances
# by duration).
curriculum = 1

[scheduler]
factor = 0.5
patience = 1
