# SPDX-License-Identifier: MIT

[model]
ncomponents = 500
covtype = "full" # "full" | "diagonal"
priortype = "categorical" # "categorical" | "stick-breaking"

[inference]
steps = 200
learning_rate = 1e-2
mini_batch_size = 300 # numbers of utterances per mini-batch
